import { RestaurantElement } from "@/types";
import { getTableSize } from "./tables";
import {
  getDefaultElementSize,
  ELEMENT_DEFINITIONS,
} from "./restaurant-elements";

export interface LayoutTemplate {
  id: string;
  name: string;
  description: string;
  restaurantType: string; // Add restaurant type for filtering
  tables: Array<{
    x: number;
    y: number;
    width: number;
    height: number;
    capacity: number;
  }>;
  elements: RestaurantElement[];
}

export const LAYOUT_TEMPLATES: LayoutTemplate[] = [
  {
    id: "restaurant-standard",
    name: "Standard Restaurant",
    description: "Classic restaurant layout with dining tables and kitchen",
    restaurantType: "restaurant",
    tables: [
      { x: 80, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 140, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 200, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 260, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 105, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 175, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 245, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 140, y: 210, ...getTableSize(6), capacity: 6 },
      { x: 220, y: 210, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        ...getDefaultElementSize("entrance"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.entrance.color,
        icon: ELEMENT_DEFINITIONS.entrance.icon,
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 350,
        y: 50,
        ...getDefaultElementSize("kitchen"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.kitchen.color,
        icon: ELEMENT_DEFINITIONS.kitchen.icon,
        locked: false,
        visible: true,
      },
      {
        id: "bar-1",
        type: "bar",
        name: "Bar",
        x: 350,
        y: 150,
        ...getDefaultElementSize("bar"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.bar.color,
        icon: ELEMENT_DEFINITIONS.bar.icon,
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 300,
        ...getDefaultElementSize("bathroom"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.bathroom.color,
        icon: ELEMENT_DEFINITIONS.bathroom.icon,
        locked: false,
        visible: true,
      },
      {
        id: "storage-1",
        type: "storage",
        name: "Storage",
        x: 350,
        y: 230,
        ...getDefaultElementSize("storage"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.storage.color,
        icon: ELEMENT_DEFINITIONS.storage.icon,
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "cafe-standard",
    name: "Standard Cafe",
    description: "Cozy cafe layout with counter service and seating",
    restaurantType: "cafe",
    tables: [
      { x: 60, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 120, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 180, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 240, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 300, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 90, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 170, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 250, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 120, y: 200, ...getTableSize(6), capacity: 6 },
      { x: 220, y: 200, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        ...getDefaultElementSize("entrance"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.entrance.color,
        icon: ELEMENT_DEFINITIONS.entrance.icon,
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 380,
        y: 50,
        ...getDefaultElementSize("kitchen"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.kitchen.color,
        icon: ELEMENT_DEFINITIONS.kitchen.icon,
        locked: false,
        visible: true,
      },
      {
        id: "counter-1",
        type: "counter",
        name: "Service Counter",
        x: 380,
        y: 140,
        ...getDefaultElementSize("counter"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.counter.color,
        icon: ELEMENT_DEFINITIONS.counter.icon,
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 300,
        ...getDefaultElementSize("bathroom"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.bathroom.color,
        icon: ELEMENT_DEFINITIONS.bathroom.icon,
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "bar-standard",
    name: "Standard Bar",
    description: "Bar layout with bar seating and lounge area",
    restaurantType: "bar",
    tables: [
      { x: 80, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 140, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 200, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 260, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 320, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 100, y: 150, ...getTableSize(4), capacity: 4 },
      { x: 180, y: 150, ...getTableSize(4), capacity: 4 },
      { x: 260, y: 150, ...getTableSize(4), capacity: 4 },
      { x: 140, y: 220, ...getTableSize(6), capacity: 6 },
      { x: 240, y: 220, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        ...getDefaultElementSize("entrance"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.entrance.color,
        icon: ELEMENT_DEFINITIONS.entrance.icon,
        locked: false,
        visible: true,
      },
      {
        id: "bar-1",
        type: "bar",
        name: "Main Bar",
        x: 380,
        y: 50,
        ...getDefaultElementSize("bar"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.bar.color,
        icon: ELEMENT_DEFINITIONS.bar.icon,
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 380,
        y: 150,
        ...getDefaultElementSize("kitchen"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.kitchen.color,
        icon: ELEMENT_DEFINITIONS.kitchen.icon,
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 300,
        ...getDefaultElementSize("bathroom"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.bathroom.color,
        icon: ELEMENT_DEFINITIONS.bathroom.icon,
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "food-truck-standard",
    name: "Standard Food Truck",
    description: "Food truck layout with outdoor seating",
    restaurantType: "food-truck",
    tables: [
      { x: 60, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 120, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 180, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 240, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 90, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 170, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 120, y: 200, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        ...getDefaultElementSize("entrance"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.entrance.color,
        icon: ELEMENT_DEFINITIONS.entrance.icon,
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Food Truck Kitchen",
        x: 320,
        y: 50,
        ...getDefaultElementSize("kitchen"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.kitchen.color,
        icon: ELEMENT_DEFINITIONS.kitchen.icon,
        locked: false,
        visible: true,
      },
      {
        id: "counter-1",
        type: "counter",
        name: "Order Counter",
        x: 320,
        y: 140,
        ...getDefaultElementSize("counter"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.counter.color,
        icon: ELEMENT_DEFINITIONS.counter.icon,
        locked: false,
        visible: true,
      },
    ],
  },
];
