import { RestaurantElement } from "@/types";
import { getTableSize } from "./tables";
import {
  getDefaultElementSize,
  ELEMENT_DEFINITIONS,
} from "./restaurant-elements";

export interface LayoutTemplate {
  id: string;
  name: string;
  description: string;
  restaurantType: string; // Add restaurant type for filtering
  tables: Array<{
    x: number;
    y: number;
    width: number;
    height: number;
    capacity: number;
  }>;
  elements: RestaurantElement[];
}

export const LAYOUT_TEMPLATES: LayoutTemplate[] = [
  {
    id: "restaurant-intimate",
    name: "Intimate Restaurant",
    description: "Perfect for fine dining with 20-30 seats",
    restaurantType: "restaurant",
    tables: [
      { x: 80, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 140, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 200, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 260, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 105, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 175, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 245, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 140, y: 210, ...getTableSize(6), capacity: 6 },
      { x: 220, y: 210, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        ...getDefaultElementSize("entrance"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.entrance.color,
        icon: ELEMENT_DEFINITIONS.entrance.icon,
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 350,
        y: 50,
        ...getDefaultElementSize("kitchen"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.kitchen.color,
        icon: ELEMENT_DEFINITIONS.kitchen.icon,
        locked: false,
        visible: true,
      },
      {
        id: "bar-1",
        type: "bar",
        name: "Wine Bar",
        x: 350,
        y: 150,
        ...getDefaultElementSize("bar"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.bar.color,
        icon: ELEMENT_DEFINITIONS.bar.icon,
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 300,
        ...getDefaultElementSize("bathroom"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.bathroom.color,
        icon: ELEMENT_DEFINITIONS.bathroom.icon,
        locked: false,
        visible: true,
      },
      {
        id: "storage-1",
        type: "storage",
        name: "Storage",
        x: 350,
        y: 230,
        ...getDefaultElementSize("storage"),
        rotation: 0,
        color: ELEMENT_DEFINITIONS.storage.color,
        icon: ELEMENT_DEFINITIONS.storage.icon,
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "restaurant-casual",
    name: "Casual Restaurant",
    description: "Family-friendly layout with 40-50 seats",
    restaurantType: "restaurant",
    tables: [
      { x: 60, y: 80, ...getTableSize(4), capacity: 4 },
      { x: 125, y: 80, ...getTableSize(4), capacity: 4 },
      { x: 190, y: 80, ...getTableSize(4), capacity: 4 },
      { x: 255, y: 80, ...getTableSize(4), capacity: 4 },
      { x: 320, y: 80, ...getTableSize(4), capacity: 4 },
      { x: 85, y: 145, ...getTableSize(6), capacity: 6 },
      { x: 160, y: 145, ...getTableSize(6), capacity: 6 },
      { x: 235, y: 145, ...getTableSize(6), capacity: 6 },
      { x: 310, y: 145, ...getTableSize(6), capacity: 6 },
      { x: 120, y: 220, ...getTableSize(8), capacity: 8 },
      { x: 205, y: 220, ...getTableSize(8), capacity: 8 },
      { x: 50, y: 310, ...getTableSize(10), capacity: 10 },
      { x: 150, y: 310, ...getTableSize(12), capacity: 12 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        width: 120,
        height: 70,
        rotation: 0,
        color: "#10b981",
        icon: "DoorOpen",
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 400,
        y: 50,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#f59e0b",
        icon: "ChefHat",
        locked: false,
        visible: true,
      },
      {
        id: "counter-1",
        type: "counter",
        name: "Service Counter",
        x: 400,
        y: 150,
        width: 90,
        height: 60,
        rotation: 0,
        color: "#ef4444",
        icon: "Building2",
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 310,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#06b6d4",
        icon: "Bath",
        locked: false,
        visible: true,
      },
      {
        id: "storage-1",
        type: "storage",
        name: "Storage",
        x: 400,
        y: 230,
        width: 80,
        height: 60,
        rotation: 0,
        color: "#6b7280",
        icon: "Package",
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "cafe-modern",
    name: "Modern Cafe",
    description: "Contemporary cafe with flexible seating",
    restaurantType: "cafe",
    tables: [
      { x: 60, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 120, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 180, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 240, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 300, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 360, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 80, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 150, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 220, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 290, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 140, y: 210, ...getTableSize(6), capacity: 6 },
      { x: 220, y: 210, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        width: 120,
        height: 70,
        rotation: 0,
        color: "#10b981",
        icon: "DoorOpen",
        locked: false,
        visible: true,
      },
      {
        id: "counter-1",
        type: "counter",
        name: "Coffee Bar",
        x: 420,
        y: 100,
        width: 90,
        height: 60,
        rotation: 0,
        color: "#ef4444",
        icon: "Building2",
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 420,
        y: 180,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#f59e0b",
        icon: "ChefHat",
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 290,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#06b6d4",
        icon: "Bath",
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "cafe-cozy",
    name: "Cozy Cafe",
    description: "Intimate cafe with warm atmosphere",
    restaurantType: "cafe",
    tables: [
      { x: 70, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 130, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 190, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 250, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 100, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 170, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 240, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 140, y: 210, ...getTableSize(6), capacity: 6 },
      { x: 210, y: 210, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        width: 120,
        height: 70,
        rotation: 0,
        color: "#10b981",
        icon: "DoorOpen",
        locked: false,
        visible: true,
      },
      {
        id: "counter-1",
        type: "counter",
        name: "Coffee Bar",
        x: 330,
        y: 100,
        width: 90,
        height: 60,
        rotation: 0,
        color: "#ef4444",
        icon: "Building2",
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 330,
        y: 180,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#f59e0b",
        icon: "ChefHat",
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 290,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#06b6d4",
        icon: "Bath",
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "bar-lounge",
    name: "Bar & Lounge",
    description: "Sophisticated bar with lounge seating",
    restaurantType: "bar",
    tables: [
      { x: 50, y: 120, ...getTableSize(2), capacity: 2 },
      { x: 110, y: 120, ...getTableSize(2), capacity: 2 },
      { x: 170, y: 120, ...getTableSize(2), capacity: 2 },
      { x: 230, y: 120, ...getTableSize(2), capacity: 2 },
      { x: 290, y: 120, ...getTableSize(2), capacity: 2 },
      { x: 80, y: 180, ...getTableSize(4), capacity: 4 },
      { x: 150, y: 180, ...getTableSize(4), capacity: 4 },
      { x: 220, y: 180, ...getTableSize(4), capacity: 4 },
      { x: 290, y: 180, ...getTableSize(4), capacity: 4 },
      { x: 110, y: 250, ...getTableSize(6), capacity: 6 },
      { x: 190, y: 250, ...getTableSize(6), capacity: 6 },
      { x: 270, y: 250, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        width: 120,
        height: 70,
        rotation: 0,
        color: "#10b981",
        icon: "DoorOpen",
        locked: false,
        visible: true,
      },
      {
        id: "bar-1",
        type: "bar",
        name: "Bar Counter",
        x: 370,
        y: 100,
        width: 80,
        height: 60,
        rotation: 0,
        color: "#8b5cf6",
        icon: "Wine",
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 370,
        y: 180,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#f59e0b",
        icon: "ChefHat",
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 340,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#06b6d4",
        icon: "Bath",
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "bar-pub",
    name: "Pub Style",
    description: "Traditional pub with communal seating",
    restaurantType: "bar",
    tables: [
      { x: 60, y: 100, ...getTableSize(4), capacity: 4 },
      { x: 125, y: 100, ...getTableSize(4), capacity: 4 },
      { x: 190, y: 100, ...getTableSize(4), capacity: 4 },
      { x: 255, y: 100, ...getTableSize(4), capacity: 4 },
      { x: 320, y: 100, ...getTableSize(4), capacity: 4 },
      { x: 90, y: 165, ...getTableSize(6), capacity: 6 },
      { x: 165, y: 165, ...getTableSize(6), capacity: 6 },
      { x: 240, y: 165, ...getTableSize(6), capacity: 6 },
      { x: 315, y: 165, ...getTableSize(6), capacity: 6 },
      { x: 120, y: 240, ...getTableSize(8), capacity: 8 },
      { x: 200, y: 240, ...getTableSize(8), capacity: 8 },
      { x: 280, y: 240, ...getTableSize(8), capacity: 8 },
      { x: 50, y: 330, ...getTableSize(15), capacity: 15 },
      { x: 180, y: 330, ...getTableSize(20), capacity: 20 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        width: 120,
        height: 70,
        rotation: 0,
        color: "#10b981",
        icon: "DoorOpen",
        locked: false,
        visible: true,
      },
      {
        id: "bar-1",
        type: "bar",
        name: "Bar Counter",
        x: 400,
        y: 100,
        width: 80,
        height: 60,
        rotation: 0,
        color: "#8b5cf6",
        icon: "Wine",
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Kitchen",
        x: 400,
        y: 180,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#f59e0b",
        icon: "ChefHat",
        locked: false,
        visible: true,
      },
      {
        id: "bathroom-1",
        type: "bathroom",
        name: "Bathroom",
        x: 50,
        y: 330,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#06b6d4",
        icon: "Bath",
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "food-truck-outdoor",
    name: "Food Truck + Outdoor",
    description: "Food truck with outdoor seating area",
    restaurantType: "food-truck",
    tables: [
      { x: 80, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 140, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 200, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 260, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 320, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 100, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 170, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 240, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 310, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 130, y: 210, ...getTableSize(6), capacity: 6 },
      { x: 210, y: 210, ...getTableSize(6), capacity: 6 },
      { x: 290, y: 210, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        width: 120,
        height: 70,
        rotation: 0,
        color: "#10b981",
        icon: "DoorOpen",
        locked: false,
        visible: true,
      },
      {
        id: "counter-1",
        type: "counter",
        name: "Order Window",
        x: 420,
        y: 100,
        width: 90,
        height: 60,
        rotation: 0,
        color: "#ef4444",
        icon: "Building2",
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Food Truck",
        x: 420,
        y: 180,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#f59e0b",
        icon: "ChefHat",
        locked: false,
        visible: true,
      },
    ],
  },
  {
    id: "food-truck-compact",
    name: "Compact Food Truck",
    description: "Small food truck with limited seating",
    restaurantType: "food-truck",
    tables: [
      { x: 70, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 130, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 190, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 250, y: 80, ...getTableSize(2), capacity: 2 },
      { x: 100, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 170, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 240, y: 140, ...getTableSize(4), capacity: 4 },
      { x: 130, y: 210, ...getTableSize(6), capacity: 6 },
      { x: 210, y: 210, ...getTableSize(6), capacity: 6 },
    ],
    elements: [
      {
        id: "entrance-1",
        type: "entrance",
        name: "Main Entrance",
        x: 50,
        y: 50,
        width: 120,
        height: 70,
        rotation: 0,
        color: "#10b981",
        icon: "DoorOpen",
        locked: false,
        visible: true,
      },
      {
        id: "counter-1",
        type: "counter",
        name: "Order Window",
        x: 330,
        y: 100,
        width: 90,
        height: 60,
        rotation: 0,
        color: "#ef4444",
        icon: "Building2",
        locked: false,
        visible: true,
      },
      {
        id: "kitchen-1",
        type: "kitchen",
        name: "Food Truck",
        x: 330,
        y: 180,
        width: 100,
        height: 70,
        rotation: 0,
        color: "#f59e0b",
        icon: "ChefHat",
        locked: false,
        visible: true,
      },
    ],
  },
];
